apiVersion: v1
kind: Namespace
metadata:
  name: demo-xpra
---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  namespace: demo-xpra
  name: "demo-xpra-mdns"
spec:
  config: '{
      "cniVersion": "0.3.0",
      "type": "macvlan",
      "master": "vlan.200",
      "mode": "bridge",
      "ipam": {
   }
}'
