#!/bin/bash

REGISTRY='registry.demo.xpra:5443/xpra-iptables'
export REGISTRY



CONTAINER=${1:-`buildah from centos:stream8`}
(
cat <<EOF
#!/bin/bash
[ -f /etc/profile.d/lang.sh ] && source /etc/profile.d/lang.sh 
yum makecache
yum install -y wget curl
yum -y install epel-release

cd /etc/yum.repos.d/
yum install -y iptables

rpm -ev --nodeps dracut NetworkManager dracut-squash dracut-network linux-firmware NetworkManager-wifi \
	         wpa_supplicant > /dev/null 2>&1
exit 0
EOF
) | buildah run ${CONTAINER} bash

if [ "${REGISTRY}" != '' ]
then
IMAGE=`buildah commit ${CONTAINER}`

echo ${IMAGE}

podman tag ${IMAGE} ${REGISTRY}
podman push  ${REGISTRY}
fi
