#  Destinations /srv/to-container/xpra-proxy/sshd/os-root/...
---
- name: 
  hosts: localhost
  connection: local

  vars:
    ldap_server: "idm01.demo.xpra"
    playbook_name: "{{ (lookup('file', '/proc/self/cmdline') | regex_replace('\u0000',' ')).split()|select('match','^[a-z-_/]*[.]y[a]*ml')|list|first }}"

  tasks:

    - name: "playbook name {{ playbook_name }}"
      shell: date

    - name: Get XPRA_TOPDIR_INT environment variable
      set_fact:
           xpra_topdir_int: "{{ lookup('env', 'XPRA_TOPDIR_INT')  }}"

    - name: "Create path for certificates"
      file:
        path: "{{ item }}"
        state: directory
        mode: '0755'
      with_items:
      - "{{ xpra_topdir_int }}/to-container/xpra-proxy/sshd/os-root/etc/ipa"
      - "{{ xpra_topdir_int }}/to-container/common/cms/os-root/etc/ipa"
      when: ldap_server is defined

    - name: Obtain certificate for ldap provider for sssd
      get_url:
          url: "http://{{ ldap_server }}/ipa/config/ca.crt"
          dest: "{{ item }}"
      with_items:
      - "{{ xpra_topdir_int }}/to-container/xpra-proxy/sshd/os-root/etc/ipa/ca.crt"
      - "{{ xpra_topdir_int }}/to-container/common/cms/os-root/etc/ipa/ca.crt"
      when: ldap_server is defined
      delegate_to: localhost

    - name: "Create path for sssd.conf files"
      file:
        path: "{{ item }}"
        state: directory
        mode: '0700'
      with_items:
      - "{{ xpra_topdir_int }}/to-container/common/cms/ansible/etc/sssd"
      - "{{ xpra_topdir_int }}/to-container/xpra-proxy/sshd/os-root/etc/sssd"
      when: ldap_server is defined

    - name: "Copy SSSD conf to {{ xpra_topdir_int }}/to-container/xpra-proxy/sshd/os-root/etc/sssd/sssd.conf -- sshd container"
      copy:
         #
         # Source: /srv/ansible/playbooks/sssd-xpra-proxy.yaml
         #
         mode: '0600'
         dest: "{{ xpra_topdir_int }}/to-container/xpra-proxy/sshd/os-root/etc/sssd/sssd.conf"
         backup: yes
         content: |
          [domain/demo.xpra]
          override_shell = {{ xpra_topdir_int }}/sbin/xpra_x-session
          id_provider = ldap
          auth_provider = ldap
          chpass_provider = ldap
          ldap_uri = ldap://{{ ldap_server }}
          ldap_search_base = dc=demo,dc=xpra
          ldap_id_use_start_tls = True
          cache_credentials = True
          ldap_tls_reqcert = allow
          ldap_tls_cacert = /etc/ipa/ca.crt

          [sssd]
          services = nss, pam
          #, ssh
          domains = demo.xpra

          [nss]
          homedir_substring = /home
          
          [pam]

      run_once: yes
      when: ldap_server is defined
      delegate_to: localhost

    - name: "Copy SSSD conf to  {{ xpra_topdir_int }}/to-container/common/cms/ansible/etc/sssd/sssd.conf -- creator (ansible) container"
      copy:
         mode: '0600'
         dest: "{{ xpra_topdir_int }}/to-container/common/cms/ansible/etc/sssd/sssd.conf"
         backup: yes
         content: |
          [domain/demo.xpra]
          id_provider = ldap
          autofs_provider = ldap
          auth_provider = ldap
          chpass_provider = ldap
          ldap_uri = ldap://{{ ldap_server }}
          ldap_search_base = dc=demo,dc=xpra
          ldap_id_use_start_tls = True
          cache_credentials = True
          ldap_tls_reqcert = allow
          ldap_tls_cacert = /etc/ipa/ca.crt

          [sssd]
          services = nss, pam, ssh
          domains = demo.xpra

          [nss]
          homedir_substring = /home
          
          [pam]
          
          [ssh]

      run_once: yes
      when: ldap_server is defined
      delegate_to: localhost
